"Beautiful things happen when you distance yourself from negativity",
"The positive thinker sees the invisible, feels the intangible, and achieves the impossible...Winston Churchill",
"A great attidue becomes a great day which becomes a great month which becomes a greay year which becomes a great life...Mandy Hale",
"Life is 10 percent what happens to us and 90 percent how we react to it...Dennis P. Kimbro",
"One small positive thought in the morning can change your whole day",
"If ever you find yourself doubting you can make it though a challenge, simply think back to everything you've overcome in the past...Karen Salmansohn",
"Once you replace negative thoughts with positive ones, you'll start having positive results...Willie Nelson",
"Wake up, smile, and tell yourself, today is my day!",
"Only in the darkness can you see the stars... Martin Luther King, Jr.",
"Keep your face to the sunshine, and you cannot see a shadow...Helen Keller",
"Even if you're on the right track, you'll get run over if you just sit there...Will Rogers",
"Life is not about waiting for the storm to pass, it's about learning to dance in the rain",
"Believe you can and you're halfway there...Theodore Roosevelt",
"Those who don't believe in magic will never find it...Roald Dahl",
"You don't always need a plan. Sometimes you just need to breathe, trust, let go, and see what happens...Mandy Hale",
"Wake up every morning with the thought that something wonderful is about to happen",
"Before Alice got to Wonderland she had to fall",
"Be thankful for what you have, you'll end up having more. If you concentrate on what you don't have, you will never, ever have enough...Oprah Winfrey",
"Don't be a rock when you really are a gem... Lauryn Hill",
"There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is...Albert Einstein",
"Sometimes the most important thing in a whole day is the rest we take between two deep breaths...Etty Hillesum",
"The most powerful weapon on earth is the human soul on fire...Ferdinand Foch",
"Do your little bit of good where you are, it is those little bits of good put together that overwhelm the world...Desmond Tutu",
"I will go anywhere as long as it's forward...David Livingston",
"Today we will live in the moment unless it's unpleasant in which case me will eat cookie...Cookie Monster",
"Failure is the opportunity to begin again more intelligently...Henry Ford",
"Stop being afraid of what could go wrong and think of what could go write",
"Tough times never last, but tough people do...Robert H. Shuller",
"You cannot stop the waves but you can learn to surf!...Jon Kabat-Zinn",
"People who are crazy enough to think they change change the world, are the ones that do...Steve Jobs"

